Make DirectoryObject recognize various init variables
pyiron/pyiron_workflow pull request #216
Opened 2024-02-20 08:20 UTC by samwaseda

I guess this is the first one to be merged. Sorry for going back and forth all the time!

2024-02-20 08:26 UTC, samwaseda commented
@liamhuber I made [this project](https://github.com/orgs/pyiron/projects/13/views/1) to make a better overview. Hopefully it helps a bit.

2024-02-20 22:04 UTC, liamhuber requested changes
Missing a test case, but otherwise lgtm

2024-02-20 22:04 UTC, liamhuber commented on tests/unit/snippets/test_files.py
> +    def test_directory_instantiation(self):
Missing the case of instantiation by string

2024-02-21 22:02 UTC, samwaseda commented
Since the distinction won't be needed if [`DirectoryObject` is derived from `Path`](https://github.com/pyiron/pyiron_workflow/issues/218), I close this PR.

2024-02-21 22:02 UTC, closed without merging